In [6]:
import numpy as np
arr = np.array((1,2,3,4,5,6))
print(arr)

[1 2 3 4 5 6]


In [7]:
print(arr.ndim)

1


In [10]:
arr = np.array([1,2,3],ndmin = 5)
print(arr)

[[[[[1 2 3]]]]]


In [16]:
arr = np.array([[1,1,1],[2,2,2,]])
print(arr)
print(arr[1])
print(arr[-1,-1])

[[1 1 1]
 [2 2 2]]
[2 2 2]
2


In [18]:
# arr = np.array([1, 2, 3, 4, 5, 6, 7])

# print(arr[-3:-1])
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [19]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )v

In [27]:
arr = np.array([1,2,3,4,5,6],dtype='O')
print(arr.dtype)

object


In [35]:
#Astype type conversion
#always assign it to new array cant change the original array
newar = arr.astype('S')
print(newar.dtype)

|S1


In [36]:
#copy and view 
# copy copies the total array and any changes in it wont affect the original array and view is ulta it affects
n = arr.copy()
n[1] = [1,1,1,1]
v = arr.view()
v[0] = [0,0,0]
print(arr,n,v)

[list([0, 0, 0]) 2 3 4 5 6] [1 list([1, 1, 1, 1]) 3 4 5 6] [list([0, 0, 0]) 2 3 4 5 6]


In [37]:
#shaping an array
#(2,4) 2 is the number of array 4 is the elements inside each array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [40]:
arr = np.array([[1,2,3,4,5,6],[1,1,2,2,3,3]], ndmin = 5)
print(arr.shape)
#always last to first last number here 6 implies 6 elements in each array then nxt 2 implies 2 6 elemented array and then 1 such
#array 1 such array and 1 such array so totally shape is (1,1,1,2,6)

(1, 1, 1, 2, 6)


In [58]:
#reshape

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,3,2)
print(newarr)

#-1 if u dont know how many such ele/array u wanna hav
newarr = arr.reshape(2,2,-1)
print(newarr)

#flatten array
newarr = arr.flatten()
print(newarr)

#or
newarr = arr.reshape(-1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [61]:
#ndenumerate

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [62]:
#add subtract multiply divide
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,4])
a = np.add(arr1,arr2)
s = np.subtract(arr1,arr2)
m = np.multiply(arr1,arr2)
d = np.divide(arr1,arr2)
print(a,s,m,d)

[2 4 7] [ 0  0 -1] [ 1  4 12] [1.   1.   0.75]


In [68]:
#join or concatenate
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)
#column wise concating [1,2 ] and [5,6] if axis = 1 meaning columnwise
print(arr)
arr = np.concatenate((arr1, arr2))
#along rows
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [71]:
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
n=np.stack((arr1,arr2))
n
#vstack()  to stack along columns.
#hstack()  to stack along single faltten array.

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [72]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [74]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [78]:
#split the array

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 10)
#no error if 10
print(newarr)
#Split the array in 3 parts: its arndom ig

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [81]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 5)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [82]:
#Search

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [85]:
#The number 7 should be inserted on index 1 to remain the sort order.
arr = np.array([6, 7, 7, 7])

x = np.searchsorted(arr, 9)

print(x)


4


In [87]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)
#Multiple values

[1 2 3]


In [88]:
#sort
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [89]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [90]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [91]:
#filter just passin the condition in [] u can also pass an array having size or dimension same as the original array
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
